name: Build and Push Docker Image  
on:  
  push:  
    branches:  
      - no-Nginx  # 当推送到 no-Nginx 分支时触发工作流  
  workflow_dispatch:  # 允许手动触发  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Check out code  
        uses: actions/checkout@v2  

      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKER_USERNAME }}  # 从秘密中获取 Docker Hub 用户名  
          password: ${{ secrets.DOCKER_PASSWORD }}  # 从秘密中获取 Docker Hub 密码  

      - name: Build Docker image  
        run: |  
          IMAGE_NAME=${{ github.event.repository.name }}  
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest .  

      - name: Push Docker image  
        run: |  
          IMAGE_NAME=${{ github.event.repository.name }}  
          docker push ${{ secrets.DOCKER_USERNAME }}/${IMAGE_NAME}:latest
