name: Build and Push Docker Image  

on:  
  push:  
    branches:  
      - no-Nginx  # 当推送到 no-Nginx 分支时触发工作流  
  workflow_dispatch:  # 允许手动触发  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      # 检出代码  
      - name: Checkout code  
        uses: actions/checkout@v2  

      # 登录 Docker Hub  
      - name: Log in to Docker Hub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # 构建 Docker 镜像  
      - name: Build Docker image  
        run: docker build . -t your-dockerhub-username/your-image-name:latest  

      # 推送 Docker 镜像  
      - name: Push Docker image  
        run: docker push your-dockerhub-username/your-image-name:latest
